### PR TITLE
added notifications

### PR DESCRIPTION
**Pull request by alexgul1**

### CODE REVIEW

**Review by Ikilonchic — COMMENTED** [review]
All notifications must be inside action creators. In successful cases.

**Comment by Ikilonchic** [comment]
We can also notify the user about errors.

**Comment by alexgul1** [comment]
> All notifications must be inside action creators. In successful cases.

it makes sense to be

**Comment by matroskin062** [comment]
Could u make notifications on login and logout?

**Comment by alexgul1** [comment]
> > All notifications must be inside action creators. In successful cases.
> 
> it makes sense to be

updated in 67d3b5df51fc3da11da80d1e7daeb75bf2a70822

**Comment by alexgul1** [comment]
> Could u make notifications on login and logout?

added in 249481403232d30fc41c5b9199043f9feac13978

**Review by matroskin062 — APPROVED** [review]

**Review by Ikilonchic — APPROVED** [review]

**Pull request merged**
